# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x03\x61pi\".\n\x05Hello\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x16\n\x06Status\x12\x0c\n\x04tsid\x18\x01 \x01(\x03\"\'\n\x0bToTranslate\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x81\x01\n\x0fTranslateResult\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x32\n\x07results\x18\x01 \x03(\x0b\x32!.api.TranslateResult.ResultsEntry\x1a.\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\rRecordMessage\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\x1f\n\x0cStoreSummary\x12\x0f\n\x07written\x18\x01 \x01(\x03\x32\x95\x01\n\x07Welcome\x12\x1f\n\x02Hi\x12\n.api.Hello\x1a\x0b.api.Status0\x01\x12\x37\n\tTranslate\x12\x10.api.ToTranslate\x1a\x14.api.TranslateResult(\x01\x30\x01\x12\x30\n\x05Store\x12\x12.api.RecordMessage\x1a\x11.api.StoreSummary(\x01\x62\x06proto3')
)




_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='api.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.Hello.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='api.Hello.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='api.Hello.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=64,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='api.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tsid', full_name='api.Status.tsid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=88,
)


_TOTRANSLATE = _descriptor.Descriptor(
  name='ToTranslate',
  full_name='api.ToTranslate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.ToTranslate.id', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='api.ToTranslate.text', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=129,
)


_TRANSLATERESULT_RESULTSENTRY = _descriptor.Descriptor(
  name='ResultsEntry',
  full_name='api.TranslateResult.ResultsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='api.TranslateResult.ResultsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.TranslateResult.ResultsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=261,
)

_TRANSLATERESULT = _descriptor.Descriptor(
  name='TranslateResult',
  full_name='api.TranslateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.TranslateResult.id', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='api.TranslateResult.results', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRANSLATERESULT_RESULTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=261,
)


_RECORDMESSAGE = _descriptor.Descriptor(
  name='RecordMessage',
  full_name='api.RecordMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='api.RecordMessage.message', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=295,
)


_STORESUMMARY = _descriptor.Descriptor(
  name='StoreSummary',
  full_name='api.StoreSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='written', full_name='api.StoreSummary.written', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=328,
)

_TRANSLATERESULT_RESULTSENTRY.containing_type = _TRANSLATERESULT
_TRANSLATERESULT.fields_by_name['results'].message_type = _TRANSLATERESULT_RESULTSENTRY
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['ToTranslate'] = _TOTRANSLATE
DESCRIPTOR.message_types_by_name['TranslateResult'] = _TRANSLATERESULT
DESCRIPTOR.message_types_by_name['RecordMessage'] = _RECORDMESSAGE
DESCRIPTOR.message_types_by_name['StoreSummary'] = _STORESUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), dict(
  DESCRIPTOR = _HELLO,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Hello)
  ))
_sym_db.RegisterMessage(Hello)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Status)
  ))
_sym_db.RegisterMessage(Status)

ToTranslate = _reflection.GeneratedProtocolMessageType('ToTranslate', (_message.Message,), dict(
  DESCRIPTOR = _TOTRANSLATE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ToTranslate)
  ))
_sym_db.RegisterMessage(ToTranslate)

TranslateResult = _reflection.GeneratedProtocolMessageType('TranslateResult', (_message.Message,), dict(

  ResultsEntry = _reflection.GeneratedProtocolMessageType('ResultsEntry', (_message.Message,), dict(
    DESCRIPTOR = _TRANSLATERESULT_RESULTSENTRY,
    __module__ = 'api_pb2'
    # @@protoc_insertion_point(class_scope:api.TranslateResult.ResultsEntry)
    ))
  ,
  DESCRIPTOR = _TRANSLATERESULT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TranslateResult)
  ))
_sym_db.RegisterMessage(TranslateResult)
_sym_db.RegisterMessage(TranslateResult.ResultsEntry)

RecordMessage = _reflection.GeneratedProtocolMessageType('RecordMessage', (_message.Message,), dict(
  DESCRIPTOR = _RECORDMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.RecordMessage)
  ))
_sym_db.RegisterMessage(RecordMessage)

StoreSummary = _reflection.GeneratedProtocolMessageType('StoreSummary', (_message.Message,), dict(
  DESCRIPTOR = _STORESUMMARY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StoreSummary)
  ))
_sym_db.RegisterMessage(StoreSummary)


_TRANSLATERESULT_RESULTSENTRY._options = None

_WELCOME = _descriptor.ServiceDescriptor(
  name='Welcome',
  full_name='api.Welcome',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=331,
  serialized_end=480,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hi',
    full_name='api.Welcome.Hi',
    index=0,
    containing_service=None,
    input_type=_HELLO,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Translate',
    full_name='api.Welcome.Translate',
    index=1,
    containing_service=None,
    input_type=_TOTRANSLATE,
    output_type=_TRANSLATERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Store',
    full_name='api.Welcome.Store',
    index=2,
    containing_service=None,
    input_type=_RECORDMESSAGE,
    output_type=_STORESUMMARY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WELCOME)

DESCRIPTOR.services_by_name['Welcome'] = _WELCOME

# @@protoc_insertion_point(module_scope)
